# ===================================================================
# CONFIGURACIÓN DEL MICROSERVICIO: MS-USUARIOS
# ===================================================================
spring.application.name=ms-usuarios
server.port=8090

# -------------------------------------------------------------------
# CONFIGURACIÓN DE LA BASE DE DATOS (POSTGRESQL - CLUSTER NEON)
# -------------------------------------------------------------------
spring.datasource.url=jdbc:postgresql://ep-noisy-mountain-aqympuue-pooler.c-8.us-east-1.aws.neon.tech/db_abastecimiento?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_zKcU9ku8wMGW
spring.datasource.driver-class-name=org.postgresql.Driver

# -------------------------------------------------------------------
# CONFIGURACIÓN DE PERSISTENCIA (JPA / HIBERNATE)
# -------------------------------------------------------------------
# Sincronización automática del esquema de la base de datos
spring.jpa.hibernate.ddl-auto=update

# Logging y formateo de sentencias SQL en consola para auditoría
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Especificación del dialecto PostgreSQL para la optimización de consultas
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# -------------------------------------------------------------------
# CONFIGURACIÓN DE SERVICIOS EXTERNOS
# -------------------------------------------------------------------
# Desactiva el cliente de descubrimiento Eureka en entorno de desarrollo local
eureka.client.enabled=false